baseurl = "https://feisty.one/"
title = "Purple Cyber Sec"
author = "Faith O."
copyright = "Copyright © 2020, All rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

disqusShortname = "disqus_N6rHQMk6IN"
#googleAnalytics = ""

[params]
author = "Faith O."
introDescription = "I'm a Cyber Security Threat Hunter with vast Networking experience. Interested in both offensive and defensive security. Walk with me in this random journey of discovery"
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
#instagram = ""
#linkedin = ""
twitter = "feisTTY0x1"
github = "famedfeya"
